services:
  Contexts.shared.infrastructure.security.PasswordEncryptor:
    class: ../../../contexts/shared/infrastructure/security/BcryptPasswordEncryptor

  Contexts.auth.domain.AuthRepository:
    class: ../../../contexts/auth/infrastructure/persistence/sequelize/repositories/SequelizeAuthRepository

  #### Signup:
  Contexts.auth.application.SignupUserUseCase:
    class: ../../../contexts/auth/application/signup/SignupUserUseCase
    arguments:
      [
        "@Contexts.auth.domain.AuthRepository",
        "@Contexts.shared.infrastructure.security.PasswordEncryptor",
      ]

  Contexts.auth.application.SignupUserCommandHandler:
    class: ../../../contexts/auth/application/signup/SignupUserCommandHandler
    arguments: ["@Contexts.auth.application.SignupUserUseCase"]
    tags:
      - { name: commandHandler }

  Apps.auth.controllers.SignupUserCtrl:
    class: ../controllers/SignupUserCtrl
    arguments: ["@Contexts.shared.infrastructure.CommandBus"]

  #### Login:

  Contexts.auth.application.AuthenticateUserUseCase:
    class: ../../../contexts/auth/application/authenticate/AuthenticateUserUseCase
    arguments:
      [
        "@Contexts.auth.domain.AuthRepository",
        "@Contexts.shared.infrastructure.security.PasswordEncryptor",
      ]

  Contexts.auth.application.AuthenticateUserCommandHandler:
    class: ../../../contexts/auth/application/authenticate/AuthenticateUserCommandHandler
    arguments: ["@Contexts.auth.application.AuthenticateUserUseCase"]
    tags:
      - { name: commandHandler }

  Apps.auth.controllers.LoginUserCtrl:
    class: ../controllers/LoginUserCtrl
    arguments: ["@Contexts.shared.infrastructure.CommandBus"]

  #### CommandBus:

  Contexts.shared.infrastructure.CommandBus:
    class: ../../../contexts/shared/infrastructure/CommandBus/InMemoryCommandBus
    arguments: ["!tagged commandHandler"]
