services:
  Contexts.posts.domain.PostsRepository:
    class: ../../../contexts/Post/Posts/infrastructure/persistence/sequelize/repository/PostPostgresqlRepository

  #### create:
  Contexts.posts.application.create.PostCreator:
    class: ../../../contexts/Post/Posts/application/create/PostCreator
    arguments: ["@Contexts.posts.domain.PostsRepository"]

  Contexts.posts.application.create.CreatePostCommandHandler:
    class: ../../../contexts/Post/Posts/application/create/CreatePostCommandHandler
    arguments: ["@Contexts.posts.application.create.PostCreator"]
    tags:
      - { name: commandHandler }

  Apps.posts.controllers.CreatePostPostCtrl:
    class: ../controllers/CreatePostPostCtrl
    arguments: ["@Contexts.shared.infrastructure.CommandBus"]

  #### CommandBus:

  Contexts.shared.infrastructure.CommandBus:
    class: ../../../contexts/shared/infrastructure/CommandBus/CommandBus
    arguments: ["!tagged commandHandler"]
